### ISSUE TITLE
Implement getTransaction methods

### ISSUE THREAD

**Issue by gabsn** [focustree/starknet.dart#12]
- [x] `starknet_getTransactionByHash`
- [ ] `starknet_getTransactionByBlockIdAndIndex`
- [x] `starknet_getTransactionReceipt`

Specs: https://github.com/starkware-libs/starknet-specs/blob/cad17ef605ab337981ef11b28ba5343e51ad16ee/api/starknet_api_openrpc.json#L150-L239

**Comment by prajwal27** [comment]
@gabsn  `starknet_getTransactionByBlockIdAndIndex` is not implemented it seems.

This is what I get, when I try to call
```
{
    "jsonrpc": "2.0",
    "id": 0,
    "error": {
        "code": -32601,
        "message": "method 'starknet_getTransactionByBlockIdAndIndex' not found"
    }
}
```

**Comment by prajwal27** [comment]
@gabsn 
Some of the pertaining issues/concerns with the following methods:
1. `starknet_getTransactionByHash`:
    -  the response does not have the attribute `type` and is therefore not possible to distinguish between `InvokeTxn`, `DeclareTxn` and `DeployTxn`. Currently, the response is deserialized to `InvokeTxn` by default.
    - All the properties of `Txn` are made `nullable`, and this is because the specs do not mention which properties are **required**. We might have to take a look at this in the future.
    - We get transaction hash in the form of `txn_hash`, but as per the specs, it's supposed to be `transaction_hash`.
2. `starknet_getTransactionReceipt`:
    - In the response, we do not get `status_data` , `block_hash` and `block_number`, even though it is mentioned as **required** in the specs. Hence, we have made these attributes `Nullable` in the `TxnReceipt` class.
    - As per the specs, the `TxnReceipt` is `oneOf` the `[INVOKE_TXN_RECEIPT, DECLARE_TXN_RECEIPT, DEPLOY_TXN_RECEIPT, PENDING_TXN_RECEIPT]` and there is no evident way of classifying the response into these types of receipt. Currently, we are manually checking for the presence of certain attributes for classification, which is not good practice.
