### ISSUE TITLE
Support braavos account recovery

### ISSUE THREAD

**Issue by gabsn** [focustree/starknet.dart#120]

**Comment by ptisserand** [comment]
Braavos private key derivation from mnemonic is using [BIP-044](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) with path: `m/44'/9004'/0'/0/0`

To constrains private key size, the [`grindKey`](https://github.com/authereum/starkware-monorepo/blob/51c5df19e7f98399a2f7e63d564210d761d138d1/packages/starkware-crypto/src/keyDerivation.ts#L85) function is call with `keyValLimit = StarknetCurve.EC_ORDER`:
```typescript
/*
 This function receives a key seed and produces an appropriate StarkEx key from a uniform
 distribution.
 Although it is possible to define a StarkEx key as a residue between the StarkEx EC order and a
 random 256bit digest value, the result would be a biased key. In order to prevent this bias, we
 deterministically search (by applying more hashes, AKA grinding) for a value lower than the largest
 256bit multiple of StarkEx EC order.
*/
export function grindKey (keySeed: string, keyValLimit: any) {
  const sha256EcMaxDigest = new BN(
    '1 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000',
    16
  )
  const maxAllowedVal = sha256EcMaxDigest.sub(
    sha256EcMaxDigest.mod(keyValLimit)
  )
  let i = 0
  let key = hashKeyWithIndex(keySeed, i)
  i++
  // Make sure the produced key is devided by the Stark EC order, and falls within the range
  // [0, maxAllowedVal).
  while (!key.lt(maxAllowedVal)) {
    key = hashKeyWithIndex(keySeed, i)
    i++
  }
  return key.umod(keyValLimit).toString('hex')
}
```

**Comment by fraggdiller** [comment]
> Braavos private key derivation from mnemonic is using [BIP-044](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) with path: `m/44'/9004'/0'/0/0`
> 
> To constrains private key size, the [`grindKey`](https://github.com/authereum/starkware-monorepo/blob/51c5df19e7f98399a2f7e63d564210d761d138d1/packages/starkware-crypto/src/keyDerivation.ts#L85) function is call with `keyValLimit = StarknetCurve.EC_ORDER`:
> 
> ```ts
> /*
>  This function receives a key seed and produces an appropriate StarkEx key from a uniform
>  distribution.
>  Although it is possible to define a StarkEx key as a residue between the StarkEx EC order and a
>  random 256bit digest value, the result would be a biased key. In order to prevent this bias, we
>  deterministically search (by applying more hashes, AKA grinding) for a value lower than the largest
>  256bit multiple of StarkEx EC order.
> */
> export function grindKey (keySeed: string, keyValLimit: any) {
>   const sha256EcMaxDigest = new BN(
>     '1 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000',
>     16
>   )
>   const maxAllowedVal = sha256EcMaxDigest.sub(
>     sha256EcMaxDigest.mod(keyValLimit)
>   )
>   let i = 0
>   let key = hashKeyWithIndex(keySeed, i)
>   i++
>   // Make sure the produced key is devided by the Stark EC order, and falls within the range
>   // [0, maxAllowedVal).
>   while (!key.lt(maxAllowedVal)) {
>     key = hashKeyWithIndex(keySeed, i)
>     i++
>   }
>   return key.umod(keyValLimit).toString('hex')
> }
> ```

I use this keyDerivation for Braavos wallet
```
// keyDerivation.js
import { BigNumber, utils } from "ethers";
import { ec, number } from "starknet";
import pkg from 'lodash';

const { isNumber } = pkg;


export const getStarkPair = (indexOrPath, privateKey, baseDerivationPath) => {
    const masterNode = utils.HDNode.fromSeed(BigNumber.from(privateKey).toHexString());

    const path = isNumber(indexOrPath)
        ? getPathForIndex(indexOrPath, baseDerivationPath ?? "")
        : indexOrPath;
    const childNode = masterNode.derivePath(path);
    const groundKey = grindKey(childNode.privateKey);
    return ec.getKeyPair(groundKey);
}


const getPathForIndex = (index, baseDerivationPath) => {
    return `${baseDerivationPath}/${index}`;
}


const grindKey = (keySeed) => {
    const keyValueLimit = ec.ec.n;
    if (!keyValueLimit) {
        return keySeed;
    }
    const sha256EcMaxDigest = number.toBN(
        "1 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000",
        16
    );
    const maxAllowedVal = sha256EcMaxDigest.sub(
        sha256EcMaxDigest.mod(keyValueLimit)
    );

    let i = 0;
    let key;
    do {
        key = hashKeyWithIndex(keySeed, i);
        i++;
    } while (!key.lt(maxAllowedVal));

    return "0x" + key.umod(keyValueLimit).toString("hex");
}


const hashKeyWithIndex = (key, index) => {
    const payload = utils.concat([utils.arrayify(key), utils.arrayify(index)]);
    const hash = utils.sha256(payload);
    return number.toBN(hash);
}
```
------
```
export const calculateAddressBraavos = (mnemonic) => {
    const ethersWallet = ethers.Wallet.fromMnemonic(mnemonic);

    const index = 0;
    const starkPair = getStarkPair(index, ethersWallet.privateKey, baseDerivationPath);
    const publicKey = ec.getStarkKey(starkPair);
    const privateKey = addHexPrefix(sanitizeBytes(starkPair.getPrivate("hex")));
    console.log(publicKey);
    console.log(privateKey);

    const BraavosInitializer = calcBraavosInit(publicKey);
    const BraavosProxyConstructorCallData = BraavosProxyConstructor(BraavosInitializer);

    return hash.calculateContractAddressFromHash(
        publicKey,
        BraavosProxyClassHash,
        BraavosProxyConstructorCallData,
        0
    );
}
```
But the result is not correct, I can't get correct public, private key and address

**Comment by ptisserand** [comment]
@fraggdiller Are you able to recover your testnet braavos account using the following dart script?: [recovery_braavos.dart](https://github.com/focustree/starknet.dart/blob/main/packages/starknet/example/examples/recovery_braavos.dart)

If not could you please open an issue.

Concerning your issue with javascript, I don't think this PR is the right place for asking support.
