### ISSUE TITLE
Implement getClass methods

### ISSUE THREAD

**Issue by gabsn** [focustree/starknet.dart#13]
- [x] `starknet_getClass`
- [x] `starknet_getClassHashAt`
- [x] `starknet_getClassAt`

Specs: https://github.com/starkware-libs/starknet-specs/blob/cad17ef605ab337981ef11b28ba5343e51ad16ee/api/starknet_api_openrpc.json#L240-L339

**Comment by ptisserand** [comment]
Infura JSON RPC implementation doesn't support `blockId` parameter for `starknet_getClassHashAt`

**Comment by ptisserand** [comment]
Infura JSON RPC implementation doesn't support `blockId` parameter for `starknet_getClassAt`
