### ISSUE TITLE
Implement starknet_estimateFee

### ISSUE THREAD

**Issue by gabsn** [focustree/starknet.dart#15]
https://github.com/starkware-libs/starknet-specs/blob/cad17ef605ab337981ef11b28ba5343e51ad16ee/api/starknet_api_openrpc.json#L420-L466

**Comment by prajwal27** [comment]
Some of the issues while implementing `estimateFee`

1. The `BlockId` serialization and deserialization issue is still unresolved. BlockId can be a `String` as well as a Class with a property either `blockHash` or `blockNumber`. So, we're unable to code such a model class using `freezed`.
2. The `toJson` method of a `Union` using `freezed` has an extra attribute called `runtimeType` which is not expected by the API and throws error.
