### ISSUE TITLE
Connect wallet creation logic

### ISSUE THREAD

**Issue by istornz** [focustree/starknet.dart#181]
On wallet creation flow, we need to integrate some logic from Starknet, we need some code from Starknet about:

- How to get the seed phrase?
- How to create an account? (and get the private key)
- How to deploy that account?
  - Should it be funded first? How?

We assume that only OpenZeppelin accounts are supported for now. Correct?

**Comment by ptisserand** [comment]
**/!\\ Depends on #148 /!\\**

> On wallet creation flow, we need to integrate some logic from Starknet, we need some code from Starknet about:
> 
> * How to get the seed phrase?

To generate the seed phrase, I'm using [`bip39.generateMnemonic`](https://pub.dev/documentation/bip39/latest/bip39/generateMnemonic.html)

It's a simple call:
```dart
final mnemonic = bip39.generateMnemonic().split(" ");
```

> * How to create an account? (and get the private key)
To retrieve `Account` object, here is a snippet:
```dart
  final accountDerivation = OpenzeppelinAccountDerivation(
    proxyClassHash: ozProxyClassHash,
    implementationClassHash: ozAccountUpgradableClassHash,
  );
  final account = Account.fromMnemonic(
    mnemonic: mnemonic,
    provider: provider,
    chainId: StarknetChainId.testNet,
    accountDerivation: accountDerivation,
  );
  ```

> * How to deploy that account?
>
To **deploy** this account after it have been funded, here is a snippet:
```dart
  try {
    final deployTxHash = await accountDerivation.deploy(account: account);
    print("Wait for deployed account transaction");
    final isAccepted = await waitForAcceptance(
      transactionHash: deployTxHash.toHexString(),
      provider: account.provider,
    );
    if (!isAccepted) {
      final receipt = await account.provider.getTransactionReceipt(deployTxHash);
      prettyPrintJson(receipt.toJson());
    } else {
      await printAccountInfo(account);
    }
  } catch (e) {
    print(e);
    exit(42);
  }
```
   
>   * Should it be funded first? How?

Another account should send ETH to wallet in creation adress.
Using a call like:
```dart
final provider = fundingAccount.provider;
 final txHash = await fundingAccount.send(
    recipient: recipientAddress,
    amount:
        Uint256(low: Felt(BigInt.from(0.003 * 1e18)), high: Felt.fromInt(0)),
  );
  bool isAccepted =
      await waitForAcceptance(transactionHash: txHash, provider: provider);
  if (!isAccepted) {
    print("Sending funds failed");
    return;
  }
```


> We assume that only OpenZeppelin accounts are supported for now. Correct?

Yes

**Comment by ptisserand** [comment]
Done
