### ISSUE TITLE
Add tutorial for starknet_counter

### ISSUE THREAD

**Issue by gabsn** [focustree/starknet.dart#344]

**Comment by devnet0x** [comment]
Hi, do you think i can take this issue?. I'm thinking a tutorial to clone repo, load devnet, deploy contracts,  explain starknet counter function calls and flutter run it in ubuntu.

should i run docusaurus to test the tutorial?

**Comment by ptisserand** [comment]
Hi @devnet0x , yes for sure.

It's a bit obsolete but here is a link to my [StarknetCC Paris 2023 workshop](https://github.com/ptisserand/workshop-starknetcc ) where I havve tried to explain step by step until starknet counter flutter app.

About docusaurus I don't know, wdyt @gabsn ?

**Comment by devnet0x** [comment]
PR 406 for your review.

**Comment by devnet0x** [comment]
Hi, i sent PR 406 for your review (whenever it's possible)..It has already passed checks and coderabbitai conversations have been resolved.

**Comment by ptisserand** [comment]
Closed by #406
