### ISSUE TITLE
Possible starknet-devnet version mismatch between dev environment and github workflow

### ISSUE THREAD

**Issue by ptisserand** [focustree/starknet.dart#370]
**Describe the bug**

`starknet-devnet` installation is different between github CI and developer setup.

github CI is using `starknet-devnet` docker image with version hardcoded in [.github/workflows/ci.yaml](https://github.com/focustree/starknet.dart/blob/505a28ec7b15e59a7f2fc9b4fd9dd42fadcf05b6/.github/workflows/ci.yaml#L58)
```yaml
      - name: Run starknet-devnet as a background process
        run: |
          docker run -d --name starknet-devnet \
            -v ${{ github.workspace }}/assets/devnet-dump.json:$DEVNET_DUMP_PATH \
            -p 5050:5050 \
            --entrypoint tini \
            shardlabs/starknet-devnet-rs:0.0.5 -- \
            starknet-devnet --host 0.0.0.0 --seed 0 --dump-path $DEVNET_DUMP_PATH
            sleep 3  # Wait for 3 seconds for the Docker container to initialize
```

Developer setup is done by sourcing [`.env.devnet`](https://github.com/focustree/starknet.dart/blob/505a28ec7b15e59a7f2fc9b4fd9dd42fadcf05b6/.env.devnet) and then run [`melos starknet:setup`](https://github.com/focustree/starknet.dart/blob/505a28ec7b15e59a7f2fc9b4fd9dd42fadcf05b6/melos.yaml#L29)
```yaml
  starknet:setup:
    description: Install starknet dev env
    run: |
      cargo install starknet-devnet --version $STARKNET_DEVNET_VERSION

      asdf plugin add scarb
      asdf install scarb $SCARB_VERSION
      asdf local scarb $SCARB_VERSION

      asdf plugin add starkli https://github.com/ptisserand/asdf-starkli.git
      asdf install starkli $STARKLI_VERSION
      asdf local starkli $STARKLI_VERSION

      asdf plugin add action-validator
      asdf install action-validator latest

      melos versions
```

**Expected behavior**
Developer and github CI should use the same version of `starknet-devnet`

**Comment by tonypony220** [comment]
moreover, we should bump version of starknet-devent at least to 0.0.6
cause 0.0.5 returns something other than it should (i mean it does not following JSON-RPC specs) https://github.com/0xSpaceShard/starknet-devnet-rs/blob/47ee2a73c227ee356f344ce94e5f61871299be80/crates/starknet-devnet-server/src/api/json_rpc/endpoints.rs#L195

and this issue actually blocking migrating tests
