### ISSUE TITLE
Update starknet-devnet to 0.0.6

### ISSUE THREAD

**Issue by ptisserand** [focustree/starknet.dart#371]
`starknet-devnet` should be updated to 0.0.6
 

> moreover, we should bump version of starknet-devent at least to 0.0.6
> cause 0.0.5 returns something other than it should (i mean it does not following JSON-RPC specs) https://github.com/0xSpaceShard/starknet-devnet-rs/blob/47ee2a73c227ee356f344ce94e5f61871299be80/crates/starknet-devnet-server/src/api/json_rpc/endpoints.rs#L195
> 
>
> and this issue actually blocking migrating tests

_Originally posted by @tonypony220 in https://github.com/focustree/starknet.dart/issues/370#issuecomment-2163526936_
           
Depends on #370

**Comment by xJeffx23** [comment]
Hello, I would like to participate, I have an idea of ​​what can help: update the dependency, adjust and review the code, if you give me the opportunity I could participate for my first contribution, thanks, I'll stay tuned!

**Comment by ptisserand** [comment]
Fixed with #384
