### ISSUE TITLE
Smart contract check is missing in github CI

### ISSUE THREAD

**Issue by ptisserand** [focustree/starknet.dart#389]
**Is your feature request related to a problem? Please describe.**
Smart contract are not checked for compilation error in github CI

**Describe the solution you'd like**
Smart contract shall be checked for compilation error in github CI

**Additional context**
- `scarb check` should be used (no need to generate contracts artifact for this CI jobs)
- job should be only run when there is modification in contracts
- `scarb check` should be runned with a melos command (**Edited 2024-08-03**)

**Comment by adrianvrj** [comment]
Hi, can I work on this?

**Comment by ptisserand** [comment]
> Hi, can I work on this?

For sure! Contact me if you need more information
