### ISSUE TITLE
Any plan to add transactions v3 support?

### ISSUE THREAD

**Issue by gtmickey** [focustree/starknet.dart#394]
**Is your feature request related to a problem? Please describe.**
Any plan to add transactions v3 support?

**Describe the solution you'd like**
currently v0/v1 is Deprecated,  https://docs.starknet.io/architecture-and-concepts/network-architecture/transactions/#transaction_versioning

**Describe alternatives you've considered**
<img width="755" alt="image" src="https://github.com/user-attachments/assets/8b245344-f247-4a78-83ac-b76b2c0f4313">

**Additional context**
[transactions v3 field](https://docs.starknet.io/architecture-and-concepts/network-architecture/transactions/#v3_transaction_fields)

**Comment by ptisserand** [comment]
Here are the corresponding issue:  #339 #340 #341

**Comment by ShantelPeters** [comment]
@gtmickey can I work on this

**Comment by ptisserand** [comment]
> @gtmickey can I work on this

Hi, on which sub issue do you want to work on ?
- #339 
- #340 
- #341

**Comment by ptisserand** [comment]
Closed by #423
